"""Strategy: FIGARCH (Baillie, Bollerslev & Mikkelsen 1996) long-memory
volatility regime gate + SMA trend filter.

Hypothesis (see knowledge_base/strategies_log.jsonl for this iteration's id):
Per Baillie, Bollerslev & Mikkelsen (1996), formula confirmed via the
`rugarch` R package vignette (Section 2.2.10, FIGARCH -- same PDF already
read this cron trigger for the Component GARCH, TGARCH, NAGARCH, and
apARCH entries, fifth distinct submodel consulted). Genuinely novel for
this repo (0 prior "FIGARCH"/"fractionally integrated GARCH"/"long memory
volatility" hits): every other GARCH-family model tested this cron trigger
(plain, GJR, EGARCH, Component, TGARCH, NAGARCH, apARCH) assumes shocks
decay at an EXPONENTIAL rate (persistence alpha+beta<1 with geometric
decay), but FIGARCH replaces the standard (1-L) difference operator with a
FRACTIONAL differencing operator (1-L)^d, 0<d<1, giving volatility shocks
a slower HYPERBOLIC decay rate -- a genuinely different persistence
STRUCTURE, not just a different asymmetry/power-law functional form like
the prior 6 GARCH-family entries.

FIGARCH(1,d,1) implemented via the standard ARCH(infinity) representation
(truncated to `trunc_lags` terms, standard practice per Baillie et al.
1996's own truncation approach for practical estimation):

    sigma_t^2 = omega* + sum_{k=1}^{trunc_lags} lambda_k * eps_{t-k}^2

where the lambda_k weights are generated by the standard FIGARCH(1,d,1)
recursion (Baillie et al. 1996, Chung 1999 parameterization):

    pi_0 = 1,  pi_k = pi_{k-1} * (k-1-d) / k          (fractional-diff weights)
    lambda_1 = phi - beta + d
    lambda_k = beta*lambda_{k-1} + (pi_k - phi*pi_{k-1})   for k >= 2

MLE fit (Normal innovations, same convention as this repo's other
from-scratch GARCH-family strategies) via `scipy.optimize.minimize`,
imposing 0<d<1, fit ONCE on the full available price history. Applies this
same cron trigger's own 9x-validated trend-filter AND-gate pattern.

Interface contract for validators (see validation/validators.py):
    generate_returns(price_df, **params) -> pd.Series
    generate_signals(price_df, **params) -> pd.Series
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from scipy.optimize import minimize


def _prep(price_df: pd.DataFrame) -> pd.DataFrame:
    df = price_df.copy()
    if "timestamp" in df.columns:
        df = df.set_index("timestamp")
    df = df.sort_index()
    return df


def _figarch_lambda_weights(d: float, phi: float, beta: float, trunc_lags: int) -> np.ndarray:
    """Generate the truncated FIGARCH(1,d,1) ARCH(infinity) weights lambda_k.
    Negative weights (which can arise outside the strict Chung (1999)
    positivity region) are clipped to zero -- a common pragmatic
    simplification for a from-scratch implementation avoiding the full
    positivity-constrained optimization machinery of the original paper."""
    pi = np.empty(trunc_lags + 1)
    pi[0] = 1.0
    for k in range(1, trunc_lags + 1):
        pi[k] = pi[k - 1] * (k - 1 - d) / k

    lam = np.empty(trunc_lags)
    lam[0] = phi - beta + d
    for k in range(1, trunc_lags):
        lam[k] = beta * lam[k - 1] + (pi[k + 1] - phi * pi[k])
    return np.clip(lam, 0.0, None)


def _fit_figarch(log_ret: pd.Series, trunc_lags: int = 100):
    """Fit FIGARCH(1,d,1) via MLE (Normal innovations). Returns the
    in-sample sigma2_t series."""
    eps = log_ret.dropna().to_numpy()
    eps = eps - eps.mean()
    n = len(eps)
    var_est = np.var(eps)
    eps2 = eps ** 2
    trunc = min(trunc_lags, n - 1)

    def compute_sigma2(omega, d, phi, beta):
        lam = _figarch_lambda_weights(d, phi, beta, trunc)
        sigma2 = np.full(n, var_est)
        for t in range(1, n):
            k_max = min(t, trunc)
            if k_max > 0:
                window = eps2[t - k_max:t][::-1]
                weighted = np.dot(lam[:k_max], window)
            else:
                weighted = 0.0
            sigma2[t] = omega + weighted
        return sigma2

    def neg_log_lik(params):
        omega, d, phi, beta = params
        if omega <= 0 or not (0.01 < d < 0.99) or phi < 0 or beta < 0 or beta >= 1 or phi >= 1:
            return 1e10
        try:
            sigma2 = compute_sigma2(omega, d, phi, beta)
        except Exception:
            return 1e10
        if np.any(sigma2 <= 0) or not np.all(np.isfinite(sigma2)):
            return 1e10
        ll = -0.5 * (np.log(2 * np.pi) + np.log(sigma2) + eps2 / sigma2)
        return -np.sum(ll)

    x0 = [var_est * 0.1, 0.4, 0.2, 0.5]
    try:
        res = minimize(neg_log_lik, x0, method="Nelder-Mead",
                        options={"maxiter": 3000, "xatol": 1e-7, "fatol": 1e-7})
        omega, d, phi, beta = res.x
        if omega <= 0 or not (0.01 < d < 0.99) or phi < 0 or beta < 0 or beta >= 1 or phi >= 1:
            omega, d, phi, beta = x0
    except Exception:
        omega, d, phi, beta = x0

    sigma2 = compute_sigma2(omega, d, phi, beta)
    sigma2 = np.clip(sigma2, 1e-12, None)

    idx = log_ret.dropna().index
    return pd.Series(sigma2, index=idx)


def _compute_signal_frame(price_df: pd.DataFrame, trend_window: int) -> pd.DataFrame:
    df = _prep(price_df)
    close = df["close"]
    log_ret = np.log(close.replace(0, np.nan)).diff()

    sigma2 = _fit_figarch(log_ret)
    sigma2_shifted = sigma2.shift(1).reindex(df.index)

    sma = close.rolling(trend_window).mean()
    trend_up = close > sma

    out = pd.DataFrame({"sigma2": sigma2_shifted, "trend_up": trend_up}, index=df.index)
    return out


def generate_signals(
    price_df: pd.DataFrame,
    vol_threshold_quantile: float = 0.5,
    trend_window: int = 100,
    leverage_cap: float = 1.0,
) -> pd.Series:
    """Return a position series (0 or leverage_cap, long/flat). Long when
    the FIGARCH-implied conditional variance sigma2_t is below its own
    historical `vol_threshold_quantile` (calm regime) AND
    close > SMA(trend_window)."""
    df = _prep(price_df)
    sig = _compute_signal_frame(df, trend_window)
    sigma2 = sig["sigma2"]
    trend_up = sig["trend_up"]

    threshold = sigma2.quantile(vol_threshold_quantile)
    calm = sigma2 < threshold

    position = (calm & trend_up).fillna(False).astype(float) * leverage_cap
    return position


def generate_returns(
    price_df: pd.DataFrame,
    vol_threshold_quantile: float = 0.5,
    trend_window: int = 100,
    leverage_cap: float = 1.0,
) -> pd.Series:
    """Daily strategy returns: prior-day position * that day's simple return."""
    df = _prep(price_df)
    close = df["close"]
    position = generate_signals(
        df, vol_threshold_quantile=vol_threshold_quantile, trend_window=trend_window,
        leverage_cap=leverage_cap,
    )
    daily_ret = close.pct_change().fillna(0.0)
    strat_ret = daily_ret * position.shift(1).fillna(0)
    return strat_ret
